### PR TITLE
Update to use existing discount implementation with latest Checkout interfaces

### PR DESCRIPTION
**Pull request by pdbreen**

### CODE REVIEW

**Comment by drewroberts** [comment]
I'm going to wait until we fix the test issue before we tag the checkout. That will fix this PR and many of the other packages.

**Comment by drewroberts** [comment]
We still have some issues with the User model and the current tests of this package.

**Comment by pdbreen** [comment]
@drewroberts should be ok now.

**Review by drewroberts — APPROVED** [review]
Thank you! 🌟

**Pull request merged**
